spring:
  application:
    name: rental-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: rental_service_db

eureka:
  client:
    enabled: false

inventory:
  service:
    url: http://localhost:8080


payment:
  service:
    url: http://localhost:8086