spring:
  application:
    name: booking-service
  config:
    import: "optional:configserver:http://localhost:8088"

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: booking_service_db

server:
  port: 8082
