spring:
  application:
    name: filter-service
  config:
    import: "optional:configserver:http://localhost:8088"

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: filter_service_db