spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:http://localhost:8088"

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: inventory_service_db

server:
  port: 8080